### ISSUE TITLE
file readme

### ISSUE THREAD

**Issue by redika97** [mhihanif/spksederhana#2]
gw fokus ma file readme aja.
- untuk file readme nya mgkn bisa ditambah dengan screenshot biar bisa lebih menarik.
- pada bagian petunjuk penggunaan, langkah 6 dan 7, sebaiknya opsi a,b,c dibuat kebawah biar ga memusingkan.
- pada bagian link license, code of conduct, dan contributing, seperti ada kesalah, coba cek lagi.

**Comment by mhihanif** [comment]
terima kasih idenya, saya akan coba update dalam waktu dekat.
